apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: user-service
    env: {{ .Values.env }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.image.port }}
      protocol: TCP
  selector:
    app: user
    env: {{ .Values.env }}
  type: LoadBalancer
