apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order
spec:
  ports:
    - port: 80
      targetPort: 9092
      protocol: TCP
  selector:
    app: order
  type: LoadBalancer
