apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-service
          image: bemodesty306/spring-user:20afdcfe42af6b0110b1b4f54208961cc1b34e01
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: db_port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: db_password
