apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: catalog
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaset.replicas }}
  selector:
    matchLabels:
      app: catalog
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: catalog
        env: {{ .Values.env }}
    spec:
      containers:
        - name: catalog-service
          image: {{ .Values.image.owner }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.image.port }}
          envFrom:
            - secretRef:
                name: catalog-secret-new